name: MSYS2 CI

on:
  push:
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: .local

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        shared: [OFF]
        malloy_tls: [ON, OFF]

    runs-on: windows-latest

    name: "msys2/mingw (tls: ${{ matrix.malloy_tls }}) (shared: ${{ matrix.shared }})"
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: false
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake 
            mingw-w64-x86_64-boost

      - name: Configure
        run: cmake -Bbuild -G"MSYS Makefiles" -DMALLOY_BUILD_EXAMPLES=ON -DMALLOY_BUILD_TESTS=ON -DMALLOY_FEATURE_TLS=${{ matrix.malloy_tls }} -DMALLOY_DEPENDENCY_SPDLOG_DOWNLOAD=ON -DMALLOY_BUILD_SHARED=${{ matrix.shared }}

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ./build/bin/malloy-tests
